### ISSUE TITLE
Errors in the build for Data science v2

### ISSUE THREAD

**Issue by zoelubitz** [Thinkful/eagle-flavored-thinkdown#69]
Not sure if this is an issue--was taking a look with @ripleyaffect earlier. All the Errors look concerning though... @evanrs @tholex 
![data-001-v2](https://cloud.githubusercontent.com/assets/8418836/6677368/a71139d8-cc05-11e4-8525-18c694ae3d8a.png)

**Comment by tholex** [comment]
If we migrate to thunderbird, this'll likely show up as just a warning. I'm
guessing the syllabus files are missing, that's all.
-Olex

**Comment by evanrs** [comment]
Yup, it was added to raise the visibility of missing content while we built the new splash site.

**Comment by diezguerra** [comment]
@tholex if syllabus files are missing build should fail... that shouldn't be "just a warning", given that pelican reads off that, right?

**Comment by tholex** [comment]
Syllabus info is pretty much optional in the UI except for units - the app just states the titles of each lesson and assignment if there's no other info.

A more recent build of this curriculum shows "Caution" and the file it was trying to read:

![screenshot 2015-04-09 17 02 06](https://cloud.githubusercontent.com/assets/88747/7076866/762e3e8c-deda-11e4-8397-c569e68b42ae.png)

**Comment by diezguerra** [comment]
Assuming fixed or no longer an issue. Reopen otherwise.
