### ISSUE TITLE
auto-alter embedded images to https if http

### ISSUE THREAD

**Issue by darrellsilver** [Thinkful/eagle-flavored-thinkdown#70]
http content breaks the HTTPs of eagle when published.

Or maybe force URLs of embedded elements to be HTTPs

For example: https://raw.githubusercontent.com/Thinkful-Ed/curric-data-001-v2/preview/content/4.2.7_Naive_Bayes_for_Article_Classification/content.md?token=AABfQ-i7HMqS2c6_zmgB1E69iZhjnkSxks5VFyTgwA%3D%3D

is

![screen shot 2015-03-21 at 6 02 16 pm](https://cloud.githubusercontent.com/assets/24387/6767021/6d57adba-cff4-11e4-9e12-9d89cb67f31b.png)

which renders in eagle with

![screen shot 2015-03-21 at 6 02 41 pm](https://cloud.githubusercontent.com/assets/24387/6767025/7c7552de-cff4-11e4-9deb-6760baa86c47.png)

which is

![screen shot 2015-03-21 at 6 03 02 pm](https://cloud.githubusercontent.com/assets/24387/6767030/8ac75a12-cff4-11e4-9ddf-c8fe1475af07.png)

**Comment by diezguerra** [comment]
why not do a sed replace on the curriculum .mds?

s/
\]\(https?:\/\
/
\]\(\/\/
/g

**Comment by diezguerra** [comment]
Now that I think of it, this needs to be dealt with manually, given that some providers won't offer https. Closing this.

@tholex keep in mind for your epub-to-curric. The urls should be protocol relative.

**Comment by tholex** [comment]
All epub-to-curriculum URL's will be explicitly HTTPS

**Comment by diezguerra** [comment]
@tholex for assets we control (s3), that's fine, but for things we don't we might not be able to enforce... not everyone serves SSL!

**Comment by tholex** [comment]
Epubs can't serve images from the external web ;)

I'm not modifying a tags as of yet, or just stripping them in some cases, so it shouldn't be a problem
