### ISSUE TITLE
https should be enforced for embedded elements

### ISSUE THREAD

**Issue by darrellsilver** [Thinkful/eagle-flavored-thinkdown#75]
for example, https://courses.thinkful.com/data-001v2/assignment/4.2.1 currently loads images from imgur over http, breaking the security of eagle.

**Comment by diezguerra** [comment]
@tholex did we solve in beagle by any chance?

**Comment by tholex** [comment]
For images, yes this is solved - all assets are stored in S3 and served over HTTPS.
